# Generated by Django 3.1.7 on 2021-04-07 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=1000), default=list, size=None)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('cook_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
