# Generated by Django 3.1.7 on 2024-04-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list, null=True)),
                ('instructions', models.JSONField(blank=True, default=list, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('cook_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
