# Generated by Django 3.1.7 on 2021-04-08 02:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedrecipe',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scrapedrecipe',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=1000, null=True), default=list, size=None),
        ),
    ]
