# Generated by Django 3.1.7 on 2021-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipe', '0003_auto_20210407_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedrecipe',
            name='url',
            field=models.URLField(default='https://www.delish.com', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
